### ISSUE TITLE
Breaking change: Rename linux distribution package from `newrelic-netcore20-agent` for agent version 10.0

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#1128]
The .NET Agent will no longer support .NET Core 2.0 after the planned deprecations in v10.0, but our linux distribution packages/deploy paths all reference `newrelic-netcore20-agent`.

The name of our distributed packages, deploy paths, and documentation references should use `newrelic-netcore-agent` or something similarly non-specific to a .NET Core version.

Checklist of tasks:
- [x] rename packages
- [x] choose conflict handling strategy
- [x] figure out migration of user data from previous to new package 
- [x] test upgrade scenarios with package files (rpm/dpkg)
- [x] Update and test package deploy (to APT/YUM repos) process to handle new names
- [x] test upgrade scenarios with APT/YUM
- [x] Update user documentation with new names (see https://github.com/nr-ahemsath/docs-website/tree/update-dotnet-agent-linux-package-names)
- [x] Add migration instructions to migration doc (see https://github.com/vuqtran88/docs-website/blob/dotnet-agent-10x-migration-guide/src/content/docs/apm/agents/net-agent/getting-started/9x-to-10x-agent-migration-guide.mdx)

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):* P3
*Suggested T-Shirt size (S, M, L, XL, Unknown):* M

**Comment by nr-ahemsath** [comment]
Suggested name: `newrelic-dotnet-agent` to avoid any confusion about ".NET Core 3.1" vs. ".NET 5.0".  Shouldn't be any need to explain that .NET Framework isn't supported since it's Linux. 😄 

The tricky part of this work will be that, as far as Linux package managers are concerned, `newrelic-netcore20-agent` and `newrelic-dotnet-agent` (or whatever) are totally separate and unrelated software.  We'll need to consider the following:

1. How will customers upgrade from a previous `newrelic-netcore20-agent` version to a new version?  Can we migrate their config and custom instrumentation (if any) for them?
2. How to prevent having both packages installed at the same time?  (There appear to be capabilities within the package managers to handle this: https://www.debian.org/doc/debian-policy/ch-relationships.html#conflicting-binary-packages-conflicts and https://serverfault.com/questions/396244/rpm-spec-how-to-specify-in-package-so-that-previous-rpm-is-removed)
3. Documenting and announcing this to customers so that folks who have automation to pull the latest `newrelic-netcore20-agent` package when building servers/containers know to switch to the new name if they want 10.x+

**Comment by skrivanos** [comment]
Our build pipeline broke today since the `newrelic-netcore20-agent` files are no longer included in the "latest_release" prefix. I.e. this yields no results:

https://nr-downloads-main.s3.amazonaws.com/?delimiter=/&prefix=dot_net_agent/latest_release/newrelic-netcore20-agent

Maybe stupid of us to rely on "latest_release" but some heads up would have been cool regardless!

**Comment by angelatan2** [comment]
Hello @skrivanos, thank you for bringing this to our attention!  We realized that it will be a breaking change and waited a while to make this change.  The old naming with "netcore20" was confusing since the usage was not limited to net core 2.0 and means even less since Microsoft has EOL that net core 2.0 version.  

However, with all the practical reasoning aside, you make a great point about us giving a heads up to our users.  I will pin this issue to help create visibility for the name change. Thanks again for sharing your pain point here.

**Comment by nr-ahemsath** [comment]
@skrivanos I'm sorry that our change broke your build process.  I'm curious what your thoughts are on where we could have put a "heads up" announcement that would have caught your attention (i.e. what communications channels from New Relic are you monitoring regularly)?

**Comment by skrivanos** [comment]
> @skrivanos I'm sorry that our change broke your build process. I'm curious what your thoughts are on where we could have put a "heads up" announcement that would have caught your attention (i.e. what communications channels from New Relic are you monitoring regularly)?

I'd say only e-mail and the dashboard itself and I can understand why it’s difficult (if not impossible) to identify affected users.
