### ISSUE TITLE
Integration test instability: hanging test runs

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#1198]
This is one of the common root causes of integration test instability identified by a recent analysis, shown in this internal doc: https://docs.google.com/spreadsheets/d/1TzYeQ1l11TXkQZqfYIo2IOQVFRlJ2aTdsO2Ry9xY6ag/edit#gid=0

More details as they become available.  The general problem is that some tests are hanging for some unknown reason and the test job in GHA eventually gets killed after 6 hours.

**Comment by JcolemanNR** [comment]
After reviewing recent failures, I could not identify any common patterns, or places in our code that could be causing this. 

Created a ticket with Github (likely only visible to me):
https://support.github.com/ticket/personal/0/1732402

**Comment by JcolemanNR** [comment]
Waiting on feedback from Github

**Comment by angelatan2** [comment]
The issue was filed by @JcolemanNR with Github.  However, the guidance was not useful enough for us to be able to act on it to resolve the hang when no process was created to run the integration test.  

The team could add more logging statements for integration tests to indicate when a process started as well as terminated.  Changing this ticket to Technical Debt.
