### ISSUE TITLE
Log TLS configuration closer to Agent connect

### ISSUE THREAD

**Issue by tippmar-nr** [newrelic/newrelic-dotnet-agent#1558]
### Describe the story, please be clear on scope of the story.
We currently log the TLS configuration early in startup, by inspecting `System.Net.ServicePointManager.SecurityProtocol`. It is possible for the configuration to change in a customer app (by calling the `System.Net.ServicePointManager.SecurityProtocol` setter) at any point, potentially rendering the value we logged at startup incorrect. 

Agent support staff have reported cases where it appears that the application is configured for TLS 1.0, attempts to connect and fails, then re-attempts the connection with TLS 1.2 and is successful. Logging the TLS configuration closer to the connect attempts might provide insight for the failure and eventual success of the connect attempt.

### Acceptance Criteria
TLS configuration should be logged immediately prior to connect attempts.

### Estimates
Please provide initial t-shirt size
S

**Comment by neilpdx** [comment]
I did some quick testing on this.

I can confirm that at least for my basic test app, when I don't specify TLS in app code our logging reports `System Default` and when I add...

```
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
```

...our logging reports those specific versions of TLS.

Another interesting thing is that when I initially set the `SecurityProtocol` in app code to `Tls` and have my app print the results of...

```
            Console.WriteLine($"TLS Configuration (System.Net.ServicePointManager.SecurityProtocol): {System.Net.ServicePointManager.SecurityProtocol}");
```

...the app prints `Tls` as expected.

When I change the `SecurityProtocol` to `Tls12` (later in the same app code) the app does correctly print `Tls12`.

The fix in agent 10.9.1 allows the agent to successfully connect in this scenario (due to the additional retries), but we don't log the new `Tls12` value. 

I think this would be a useful addition to our logging.
