### ISSUE TITLE
Scriptable installer not configuring the installed agent correctly

### ISSUE THREAD

**Issue by nrcventura** [newrelic/newrelic-dotnet-agent#159]
Customer Issue: 
[Zendesk 423907](https://newrelic.zendesk.com/agent/tickets/423907)

[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
If you use the scriptable installer to install the framework agent, when the agent starts up you get the following error, preventing the agent from working.

```
NewRelic ERROR: [pid: 4684, tid: 7] There was an error initializing the agent: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
at System.IO.Path.Combine(String path1, String path2)
at NewRelic.Agent.Core.Utilities.ExtensionsLoader.Initialize(String installPathExtensionsDirectory)
at NewRelic.Agent.Core.AgentManager..ctor()
at NewRelic.Agent.Core.AgentManager.AgentSingleton.CreateInstance()
```

**Expected Behavior**
The agent should not get the above error when starting up.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
N/A

**Steps to Reproduce**

1. Start with a fresh system that doesn't have New Relic installed yet.
2. Run the scriptable installer to install the agent.
3. Start an application that should be instrumented by the agent.
4. View the managed agent log and see the above error.

**Your Environment**
N/A

**Additional context**
The scriptable installer sets the NEWRELIC_INSTALL_PATH environment variable to be "C:\Program Files\New Relic\.NET Agent\". It also places the agent's files into that directory. 

When the agent starts up it using the following logic to determine the agent's installed directory.

```
        private static string GetNewRelicInstallPath()
        {
            var newRelicInstallPath = System.Environment.GetEnvironmentVariable(NewRelicInstallPathEnvironmentVariable);
            if (newRelicInstallPath != null)
            {
                newRelicInstallPath = Path.Combine(newRelicInstallPath, RuntimeDirectoryName);
                if (Directory.Exists(newRelicInstallPath)) return newRelicInstallPath;
            }

            newRelicInstallPath = System.Environment.GetEnvironmentVariable(NewRelicHomeEnvironmentVariable);
            return newRelicInstallPath;
        }
```

The problem is occurring because when the `NEWRELIC_INSTALL_PATH` environment variable is used, it will look for the agent in `netframework` subdirectory within `NEWRELIC_INSTALL_PATH`. But the scriptable installer does not place the agent bits into that subdirectory, so the agent will check the `NEWRELIC_HOME` environment variable next. However, that environment variable is not defined, so the agent's install directory will be set to `null`, which is what's causing the exception.

This has likely been broken for a while.

**Comment by nrcventura** [comment]
Some ideas for resolving this issue include:

- Use the scriptable installer to wrap the MSI installer
- Update the scriptable installer (and documentation) to use the NEWRELIC_HOME environment variable instead of NEWRELIC_INSTALL_PATH
- Update the scriptable installer (and documentation) to place the agent bits in the netframework subdirectory

**Comment by nr-ahemsath** [comment]
If we wanted to go with the option of using `NEWRELIC_HOME`, it would seem to be in addition to `NEWRELIC_INSTALL_PATH` as opposed to instead of it.

Both the .msi and the scriptable installer put some assets in `C:\Program Files\NewRelic\.NET Agent` and other assets in `C:\ProgramData\NewRelic\.NET Agent`.  However, the .msi installer (as of today) creates links from the location in `Program Files` to the corresponding real files in `ProgramData`.  Importantly, `newrelic.config` is one file like this.  The scriptable installer does not create these links.

I tested installing using the scriptable installer for the framework agent (for 8.36).  As expected, when trying to instrument a .NET Framework application, the agent could not start.  `NEWRELIC_INSTALL_PATH` was set to `C:\Program Files\NewRelic\.NET Agent`.  If I set `NEWRELIC_HOME` to the same value (the program files location), the agent still could not start.  However, if I set `NEWRELIC_HOME` to `C:\ProgramData\NewRelic\.NET Agent` (and left `NEWRELIC_INSTALL_PATH` set to the Program Files path), then the agent worked.

This brings up more questions:
1. How did this ever work before?
2. How is my scenario working, without there being a `netframework` subfolder in `C:\Program Files\NewRelic\.NET Agent` and the proper agent bits in there, since that's how it works with the .MSI?

I guess if we want a quick and dirty fix we can just add the `NEWRELIC_HOME` env var pointing to the ProgramData location.  However, I don't really like the fact that this would create a different installation layout than the .MSI installer uses.  Following the path of having the scriptable installer wrap the .MSI installer would seem to be the better path forward, but will take more effort.  Also, it would mean that users of the scriptable installer would be installing both the framework and core agents (which is not the case now).

We could try option three (update the scriptable installer(s) to act like the .msi) but this still leaves us with the technical debt of having to maintain multiple installation scripts for Windows server installs.

I wish we had data for our downloads site like NuGet gives us so we could have an idea of whether anybody is even using the scriptable installer at this point.  If we feel like we can make the scriptable installer be a wrapper around the .msi, it seems like customers who want to script installs should just use the .MSI from the command line (which we do document how to do).

**Comment by angelatan2** [comment]
If you are visiting this ticket, please note that we are planning to reduce the number of methods used to install the .NET agent so that we can provide a more streamlined install experience. If you use the scriptable install method and have concerns,  please do not hesitate to share those concerns here.  (3/1/2021)

**Comment by angelatan2** [comment]
No plans on fixing this issue in the near term.
