### ISSUE TITLE
Add MinimumLevel for logging into newrelic configuration file

### ISSUE THREAD

**Issue by miksh7** [newrelic/newrelic-dotnet-agent#1593]
Sometimes an application/website produces excessive logging with Debug level written into a file which in most cases is not relevant for the application monitoring and troubleshooting. Since NR agent logs everything, the only option now is to configure a drop filter. However, in this case it results in unnecessary network / server resources consumption which could be quite significant and impact the overall server performance.
It would be useful to add MinimumLevel for logging into newrelic configuration file to prevent processing unnecessary data.

**Comment by chynesNR** [comment]
Hi @miksh7 - thanks for your input! This is definitely on our radar and will be in a future release. It's more complex than it seems at first, since some logging frameworks allow for defining custom log levels that can make the order a bit ambiguous.

**Comment by jaffinito** [comment]
After looking into the issue in detail we are not going to be moving forward with implementing this feature for several reasons.   The primary reason is due to the various log frameworks we support not having a unified level hierarchy that we can quickly check without incurring a performance penalty. 

We are currently in the process of implementing a similar feature, Log Level Filtering, that should be able to achieve similar results.  Log Level Filtering will allow for specific log levels (any number) to be exclude using config.
