### ISSUE TITLE
Add integration tests for Devart.Data.Oracle

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#1631]
See this PR: https://github.com/newrelic/newrelic-dotnet-agent/pull/1580

We felt this was a low risk change to merge without adding integration tests, but we should still add some when we have a tech debt cycle.

**Comment by jaffinito** [comment]
A Standard edition license is needed to use the Direct connect (no Oracle client needed).  Out existing instrumentation uses the Direct method and we don't want to have to install the client since it is quite large.  Due to this we are going to close this for now and track usage of the instrumentation to see if we should explorer getting a license in the future.
