### ISSUE TITLE
Flush logs before transaction ends

### ISSUE THREAD

**Issue by santanaguy** [newrelic/newrelic-dotnet-agent#1758]
Hey everyone, I have a scenario where I need your help. I searched everywhere I could, but got no answer for it 

We have a set of .NET Framework workers which run on Docker containers. These workers use the Custom Instrumentation (through attributes) to report transactions. We're using the .NET agent running in the container side-by-side with our app.

The problem is that whenever we have long running transactions (or otherwise unexpected errors like access violation exceptions) we lose the logs entirely because the transaction never "finishes" and the logs are only reported after the transaction is finished.

Is there a way to have transactions but still flush logs? It is ok if we use the logs-in-context feature, but we need to have both the logs and the transaction information on NR.

### Additional context
* .NET Framework running on Docker Windows Container
* .NET Agent vlatest on the container
* Automatic log forwarding enabled (captured from Microsoft.Extensions.Logging)

**Comment by chynesNR** [comment]
Hi @santanaguy -- thanks for reaching out. We're a little unclear what's going on in your scenario. How long are these long transactions you're talking about? As long as they complete at some point, you should still get the logs at the end. If the transactions are very long (10s of minutes), and you have lots of log data, some of it may be discarded due to the size of our data reservoirs. If that turns out to be the case, that is a setting you could adjust.

Exceptions or errors should not prevent a transaction from finishing and sending the corresponding log data. One special case, however, is an access violation exception, because that terminates the thread, leaving us unable to complete the work. Are those the only kinds of errors causing a problem?

With the current Agent architecture, it's not possible to send logs before a transaction has completed, but hopefully we can find you a workaround.

**Comment by santanaguy** [comment]
Hi @chynesNR,

Our scenario is indeed as you described: 
* Sometimes we have very long transactions, and not seeing the logs of what is happening in the pod leaves us wondering. We can still look at the logs using kubectl but that is not very convenient of course.
* Other times we do have Access Violation Exception. That puts us in the position of losing the transaction (that is normal), but also all the logs from it. That is something we would like to workaround if possible.

The agent does log some stuff unrelated to transactions (the logs from the pods starting - like the hosting environment etc - do show up in NR).

To be clear, we would be ok with the workaround of losing all correlation to transactions but still have the ability to flush the logs. 
Would it be possible to have transactions and logs separated with no correlation, and would it then flush the logs periodically?

**Comment by chynesNR** [comment]
Understood! In that case I think you could either use [your own log-forwarder](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/#2-decorate) or the [manual approach](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/#3-old-formatter). Either way would remove the direct link to the Transaction processing cycle and get them to you sooner. Let me know if one of those might work for you.
