### ISSUE TITLE
Add an overload for  NewRelic.Api.Agent.NewRelic.NoticeError(message, exception)

### ISSUE THREAD

**Issue by malylemireflo** [newrelic/newrelic-dotnet-agent#2210]
### Is your feature request related to a problem? Please describe.
There is no way to send a logevent message with an exception to new relic.

### Feature Description
I want to be able to send a log message with an exception and it's stack trace at the same time.

### Describe Alternatives
Wrap the exception as an inner exception. But we loose the exception type.

### Priority
Must Have

**Comment by jaffinito** [comment]
Hi @malylemireflo Thank you for creating this feature request.  I would like to get some more details about the request to help us better understand what you are looking for.

- Are you looking to create a log message (logging UI) or a standard error event (Errors Inbox)?
- Normally, we create the stack trace from the exception, but it sounds like you might want to provide your own.  Am I misreading this part of your request?

**Comment by malylemireflo** [comment]
Actually I want to create a standard error event. When using LogCritical("Message", exception) we have added a custom sink to send the error to new relic in a custom transaction with attribute, I want the error in new relic to have both the exception with stack trace and the logevent message. Something like this

var exception = logEvent.Exception;
var message = logEvent.RenderMessage();
if (exception != null && message != null)
{
    NewRelic.Api.Agent.NewRelic.NoticeError(message, exception);
}

**Comment by chynesNR** [comment]
Hi @malylemireflo -- thanks for the clarification. While we could do what you're asking, our concern is that overriding the error message (usually derived from the exception object) would make it more difficult to track down the source of the error. In the scenario you've described, could you create a custom exception, with `exception` as the inner exception? That would allow you to customize the message as you like without needing a behavior change.

**Comment by malylemireflo** [comment]
Hi,

Yes like I said in the description

Describe Alternatives
Wrap the exception as an inner exception. But we loose the exception type.

We loose the exception type and every exception type is Exception or the custom exception in the ui....

**Comment by nrcventura** [comment]
In both cases, including the proposal in this request, information will be lost. 

The error model ultimately includes a type, message, and stack trace. In this proposal, the message from the exception would be replaced with the message from the log. 

In the case of a custom wrapping exception, the type would now include the wrapping exception type, but the stack trace would include the original exception type. If your wrapping type was a generic type, the name would include both types.

It also seems like it would be good for these logs that contain errors to be sent to New Relic as logs. Then if Errors Inbox could display those logs, because they have errors, that might meet your needs too.
