### ISSUE TITLE
8T Polish - Validate Kubernetes metadata transmission scenario

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#411]
One of the two user stories we are servicing in this milestone reads "As a user of Infinite Tracing, I expect to get my k8s metadata in the same way I would with the standard agent collector pipeline. Also, as a user of Infinite Tracing, I expect that I would not lose span data when New Relic redirects my traffic to a different cell."

There is an associated agent spec change, which the agent already has implemented: https://github.com/newrelic/newrelic-dotnet-agent/blob/e15fb00b8c984a079eb0c0ba014862c5b0896ba4/src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs#L162-L166

We need to validate that the user requirement has been satisfied by what we have implemented.  A manual test demonstrating that the require k8s metadata is being transmitted with 8T payloads should be sufficient.

**Comment by vuqtran88** [comment]
My validation points out the following behaviors:

   1. The agent successfully captured K8S metadata from `NEW_RELIC_METADATA_KUBERNETES_*` environment variables injected by k8s webhook.
   2. The agent sends these metadata in the Connect request.
   3. The agent receives the Connect response. The k8s metadata the agent sent up is now present in the Connect response but is encoded and stored in the `request_headers_map.nr-k8smetadata` key.
   4. The agent sends the encoded k8s metadata to the trace observer.

Even though the agent sent these metadata to the trace observer, these metadata are not yet manifested any where because the magic trace box is currently not doing anything with these metadata. With these information, I'm moving this issue to closed as the agent surely does what it is designed to do according to the specs.
