### ISSUE TITLE
Agent performance bottleneck caused by use of AppDomain.GetData() in high throughput applications

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#533]
**Description**

At least one customer has reported seeing a performance bottleneck caused by the agent in a high-throughput application.  The overhead is caused by the agent's use of `AppDomain.GetData()` to cache the results of reflection calls to get `MethodInfo` data.  This is part of the IL-rewriting profiler component of the agent.  The part of the profiler that does this can be seen here: https://github.com/newrelic/newrelic-dotnet-agent/blob/dc85233559d62679252a48e5e55d4140681b2f0f/src/Agent/NewRelic/Profiler/MethodRewriter/FunctionManipulator.h#L328

The method `GetMethodFromAppDomainStorageOrReflectionOrThrow` is one of our helper methods that are themselves bytecode-injected into the `[mscorlib]System.CannotUnloadAppDomainException` class, as can be seen here: https://github.com/newrelic/newrelic-dotnet-agent/blob/8f8ffd1e7612de5b9ff81acea8911a3fcc880175/src/Agent/NewRelic/Profiler/MethodRewriter/HelperFunctionManipulator.h#L133

**Expected Behavior**

Since this feature of the agent is intended to be a performance optimization, it should not be causing a performance bottleneck (due to the locking inside `AppDomain.GetData()`).

**Steps to Reproduce**
There is no specific repro; the customer who reported this issue only sees it intermittently in production and is unable to reproduce in a test environment.  The symptoms of the issue are a major performance bottleneck in an app with the agent attached.  If a memory dump is taken of the app in this state, a "CrashHang" analysis with the DebugDiag tool will show many threads with the following stack at the top:
```
[[HelperMethodFrame] (System.Threading.Monitor.Enter)] System.Threading.Monitor.Enter(System.Object) 
System.AppDomain.GetData(System.String)+c7 
mscorlib.dll!Unknown+3d 
mscorlib.dll!Unknown+37 
```

Note: this behavior would only occur in .NET Framework; the profiler does not do this for .NET Core apps.

Idea: since the profiler method which uses the MethodInfo caching has a boolean `useCache` parameter (currently only used to distinguish between .NET Framework and .NET Core uses of this method), it should be fairly easy to make the use of this cache a configurable parameter that users could set to false if they encounter this kind of thread contention.

Internal note: [original customer ticket](https://newrelic.zendesk.com/agent/tickets/452184)
[support ticket](https://newrelic.atlassian.net/browse/GTSE-8519)

**Comment by sberkovitz** [comment]
The way we tracked this to NR was by dumping the parameters to GetData(string). As you can see in the below snippet, the name passed to GetData is "NewRelic.Agent.Core.AgentShim.GetFinishTracerDelegate_0""


`Dumping managed stack and managed variables using ICorDebug....0000013dfcbf6438]
0000013dfcbf6530 00007ff8c93dbbf7 [DEFAULT] [hasThis] Object System.AppDomain.GetData(String)... + (Error 0x80131304 retrieving parameter 'this')
  + string name = "NewRelic.Agent.Core.AgentShim.GetFinishTracerDelegate_0"`

**Comment by sberkovitz** [comment]
You can also see the impact NR had overall on our apps lock contention rate.  Solid blue line is without NR agent, dotted blue line is with NR agent

![image](https://user-images.githubusercontent.com/11359562/115074518-cd00e300-9ec7-11eb-9961-e942212e8a53.png)

**Comment by angelatan2** [comment]
We are moving this issue into a close state.  The changes that were made for an experimental release.  The release needs to be tested in a heavily loaded system before it can be deployed in our agent. This is to ensure that our users are not negatively impacted by the change.  If this issue is similar to what you are experiencing, please comment and reach out to us.

**Comment by JcolemanNR** [comment]
We are re-opening this issue after doing some more investigation. 

We are going to be releasing a minor version of the agent which includes an environment variable to disable the use of AppDomain for method information caching. In our testing, we did see a reduction in global locks when AppDomain caching is disabled, but we also observed a decrease in application throughput. When this caching mechanism is disabled in .NET Framework applications, the agent behaves like it does for .NET Core applications and every instrumented method call must load the method signature information via reflection. This has been described as an issue for .NET Core applications in #831.

If any customers are experiencing this issue with lock contention in .NET Framework applications due to the agent invoking AppDomain.GetData(), we would be interested in having them test this new environment variable and getting feedback on if it makes the problem better/worse. 

I will post a link to the documentation when this new environment variable has released.

**Comment by angelatan2** [comment]
The change that reduces the impact of global locking was released in .NET Agent version [9.7.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9700). The configuration to enable it is documented in the release notes linked in this comment.
