### ISSUE TITLE
Improve/Create Snapshot Rollback/Rollforward Runbook for deployment

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#607]
Review our release process steps,  create/improve the run book for deployment apt.newrelic.com/debian/ rollback and roll-forward.

### Feature Description
A clear and concise description of steps required to rollback or roll forward a deployment

### Additional context
This runbook will be used to aid the process steps during incidents when necessary.

### Priority
[Must Have]

**Comment by nr-ahemsath** [comment]
Created or updated the following:

https://github.com/newrelic/newrelic-dotnet-agent/tree/main/deploy/linux#readme has been updated with the latest info on how to "manually" (i.e. from a developer machine rather than from a GHA workflow) run the APT/YUM package deploy or rollback process.

Updated the general agent rollback process documentation (NR internal): https://source.datanerd.us/dotNetAgent/dotnet-team-process/wiki/Rollback-Procedure
Created a disaster recovery document (NR internal): https://source.datanerd.us/dotNetAgent/dotnet-team-process/wiki/Rollback-Procedure

**Comment by nr-ahemsath** [comment]
This work has been completed and this issue can be closed.
