### ISSUE TITLE
Mismatched casing on constants breaks distributed tracing between Lambda and APM using sqs/sns

### ISSUE THREAD

**Issue by williamdenton** [newrelic/newrelic-dotnet-agent#652]
**Description**

The new relic tracing header use in the APM is different from that used in Lambda. The distributed trace payload is most often stored in a dictionary which is case sensitive on keys, so these traces payload is not observed correctly.

In APM:
https://github.com/newrelic/newrelic-dotnet-agent/blob/2ba99ea91ac20f79af40259e485949c6b3b1aac3/src/Agent/NewRelic.Api.Agent/Constants.cs#L31

In Lambda:
https://github.com/newrelic/newrelic-dotnet-agent/blob/2ba99ea91ac20f79af40259e485949c6b3b1aac3/src/AwsLambda/AwsLambdaOpenTracer/LambdaTracer.cs#L15

and some places where the constant should be used but isn't
https://github.com/newrelic/newrelic-dotnet-agent/blob/2ba99ea91ac20f79af40259e485949c6b3b1aac3/src/AwsLambda/AwsLambdaWrapper/LambdaWrapper.cs#L170
https://github.com/newrelic/newrelic-dotnet-agent/blob/2ba99ea91ac20f79af40259e485949c6b3b1aac3/src/AwsLambda/AwsLambdaWrapper/LambdaWrapper.cs#L200

**Expected Behavior**
The same constant value should be used in order for distributed traces to be propagated correctly

**Steps to Reproduce**
Start a distributed trace in lambda using the LambdaWrapper and SqsWrapper
Extract the header from the SQS message attributes using the constant above (this fails to find the correct payload)
As the payload is not found in the sqs attributes, `AcceptDistributedTracePayload()` can't be called. Instead, i must check for both casings of the attribute to reliable have this work.

```cs
NewRelic.Api.Agent.NewRelic.GetAgent()?.CurrentTransaction.AcceptDistributedTracePayload(,)
```

**Your Environment**
Lambda running netcore 3.1
Fullframework 4.8
Dotnetcore 3.1/5.0 on linux in docker

**Additional context**

Tracing from DotnetFX -> (via http) -> Lambda works (i guess the http headers are ok)
Tracing across sqs between dotnetfx and lambda is broken

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by JcolemanNR** [comment]
Thank you @williamdenton for identifying this issue! We will discuss in our standup tomorrow and prioritize accordingly. This seems like a simple fix to resolve issues with Distributed Tracing!

**Comment by JcolemanNR** [comment]
I'm wondering if we might want to update the rest of our system to accept case insensitivity...

**Comment by williamdenton** [comment]
this is a tricky one to solve, as this is probably used in customer code, manually calling `AcceptDistributedTracePayload()`. Trying to make it case insensitive might be difficult as its the customers code that is accessing the dictionary. Changing the value may break people that exclusively use one library or the other - or interoping with other languages/runtimes.

You customers would need to update all their services at the same time to not be broken.

The only way forward may be to obsolete which ever one of these is wrong, and advise people, and update tools like SQSWrapper to dual publish the payload under both keys until all systems in their domain are updated

**Comment by JcolemanNR** [comment]
We'll definitely have to be careful about how we roll this fix out. 

Link to internal documentation for when the team pics this up: https://source.datanerd.us/agents/agent-specs/blob/master/distributed_tracing/New-Relic-Payload.md#supported-transports

**Comment by jaffinito** [comment]
Per the Distributed Tracing spec:
When processing headers, the following cases should be accepted by the receiving app:

    All lowercase (e.g. newrelic)
    All uppercase (e.g. NEWRELIC)
    First letter capitalized, others lowercase (e.g. Newrelic)

**Comment by nr-ahemsath** [comment]
As @jaffinito pointed out, our internal distributed tracing specs require any agent participating in distributed tracing to *accept* any of the following: `newrelic`, `NEWRELIC`, `Newrelic`.

Looking at the Lambda tracer code as it currently stands, it looks like on the acceptance side we're being even more flexible and testing to see if any inbound key, lowercased, matches `newrelic`: https://github.com/newrelic/newrelic-dotnet-agent/blob/686a119865cdfb382248828ee41bd7606bacb102/src/AwsLambda/AwsLambdaOpenTracer/LambdaTracer.cs#L135

In the full agent, it looks like the method which checks for the inbound DT header will only accept `newrelic`: https://github.com/newrelic/newrelic-dotnet-agent/blob/686a119865cdfb382248828ee41bd7606bacb102/src/Agent/NewRelic/Agent/Core/DistributedTracing/TracingState.cs#L245
(`Constants.DistributedTracePayloadKey` in this context is this: https://github.com/newrelic/newrelic-dotnet-agent/blob/686a119865cdfb382248828ee41bd7606bacb102/src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Providers/Wrapper/Constants.cs#L18, which is a different constants file than the one in the `NewRelic.Api.Agent` location that was linked to in the original issue description.  According to my Visual Studio's "Find All References" function, there is no reference in the full agent solution to the constant defined in `NewRelic.Api.Agent.Constants`.)

That central method in `TracingState.cs` is what is ultimately used for accepting DT headers in both auto-instrumentation of e.g. ASP.NET Core services and manual distributed tracing with the API via `AcceptDistributedTraceHeaders`.  Note that `AcceptDistributedTracePayload` has been obsoleted as of agent version 9.x: https://docs.newrelic.com/docs/apm/agents/net-agent/net-agent-api/itransaction/#description.  The replacement method `AcceptDistributedTraceHeaders` looks for the key on its own so user code using it doesn't have to worry about which header key constant to use.

@williamdenton I know it's been a while since you wrote this up, and I apologize for the delay in looking at it.  If you're still willing and able to help, could you describe a bit more the scenario that was failing for you?  Based on your description, you have a Lambda function instrumented with our Lambda tracer, and doing distributed tracing over SQS.  What is the inbound/accepting service?  Another Lambda, or a full .NET service instrumented with the agent?

For our team: we should consider updating the DT accepting code in the full agent to be more flexible in terms of what it will accept, per the spec, and also remove that unused and obsolete constant from the API code.

**Comment by nr-ahemsath** [comment]
@williamdenton We understand that you might not have time to continue working with us on this issue.  We will close this issue in one week if we do not hear from you again.

**Comment by williamdenton** [comment]
Sorry, i have been away from work for most of January, and my focus is not currently on lambda so im not able to jump back on this at the moment. When i do return to looking at this ill update, apologies for not being able to help right now

**Comment by angelatan2** [comment]
@williamdenton thanks for letting us know.  We've returned the story to the backlog and will revisit at another time.

**Comment by angelatan2** [comment]
Hello @williamdenton, and others who are following this ticket.  There have been a lot of good discussions on this ticket over the time it was submitted.  Unfortunately, despite wanting to, we haven't gotten to it. I have to share that our current implementation of .NET AWS Lambda is based on Open Trace. The Open Trace project was archived. At this time, we do not plan on further updating the .NET AWS Lambda Open Trace agent.
