### ISSUE TITLE
.Net Core 3.1 console application isn’t reporting to New Relic. The application uses the MongoDB .Net Driver 2.7

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#743]
New Relic Agent logs:
`[Info] 2021-08-03 13:14:41 Unable to find MongoDB.Driver.MongoCollectionImpl1+MongoIndexManager for rejit. HR:-2146234064`
Followed by the agent being unloaded on the process.

In the .Net Core Agent compatibility for Datastores doc, it lists that up to 2.6 is fully supported. There is partial support for 2.7? [.NET agent: compatibility and requirements for .NET Core | New Relic Documentation 4](https://docs.newrelic.com/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core/#database)

**Expected Behavior**
The ability to find the method MongoDB.Driver.MongoCollectionImpl1+MongoIndexManager for rejit

**Additional context**
[Internal Tickets](https://newrelic.zendesk.com/agent/tickets/466438)
[Explorer Hub](https://discuss.newrelic.com/t/net-core-mongodb-driver-support/157173)

**Comment by vuqtran88** [comment]
The message `[Info] 2021-08-03 13:14:41 Unable to find MongoDB.Driver.MongoCollectionImpl1+MongoIndexManager for rejit. HR:-2146234064` is very misleading.  It doesn’t mean the profiler fails to instrument. The profiler tries to rejit all of the methods of interest in an assembly when its module is loaded to make sure rejit will happen, but there is no guarantee that it always successes. In the case of `MongoDB.Driver.MongoCollectionImpl1+MongoIndexManager` , the profiler failed to do that because it is a nested class. That's why the profiler log shows the message as `[Info]` instead of `[Error]`.

This PR update confirms that the agent does support the current latest MongoDB driver (v2.13.1).
https://github.com/newrelic/newrelic-dotnet-agent/pull/747

**Comment by vuqtran88** [comment]
Closing this as we need to gather more information about what actually broke.
