### ISSUE TITLE
Update our test environment to use log4net 2.0.10 or later

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#895]
**Description**
Please update our agent and test environment projects to use log4net version 2.0.10 or later. For example:

<PackageReference Include="log4net" Version="2.0.10" />

**Referenced in:**

- [ ] src/Agent/NewRelic/Agent/Core/Core.csproj
- [ ] tests/Agent/UnitTests/NewRelic.Agent.TestUtilities/NewRelic.Agent.TestUtilities.csproj
- [ ] tests/Agent/UnitTests/Core.UnitTest/Core.UnitTest.csproj
- [ ] tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj

Notification originated from Dependabot Alert

**Comment by vuqtran88** [comment]
When upgrading the agent to use log4net version 2.0.10 or later, even though the application and the agent still function properly (instrumentations work as expected, logging works as expected), some log4net specific exceptions were logged to STD output. This only happens to .NET Core application. It would be hard to detect this, but luckily our integration test `InstrumentationLoaderTestsCore ` does validate console output so that it detected this and failed.  

After digging, part of the issue is that the log4net 2.0.10 or later started using the `Configuration.ConfigurationManager` for .Net Core applications to read log4net configuration from different places (.ie appsettings.config, web.config, machine.config), but this library doesn't work correctly with the agent when it is ILRepacked with the agent. To be specific, any access to `AppSettings` object from this call `ConfigurationManager.AppSettings["some setting"]` from within the agent will throw the following exception:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

I found a related issue with MS and it is still not being resolved: https://github.com/dotnet/runtime/issues/32307

I haven't yet figured out a workaround to get the `Configuration.ConfigurationManager` to work in the agent yet, but a real workaround may be to use something else rather than `log4net`.
