### ISSUE TITLE
Please fix failing chocolatey package builds for new 9.x versions

### ISSUE THREAD

**Issue by jtim08515** [newrelic/newrelic-dotnet-agent#896]
Hello,

Can someone at newrelic please fix these chocolatey packages that are failing validation so we can update the the latest version?

https://community.chocolatey.org/packages/newrelic-dotnet

I'm wanting to use versions >= 9.3.0.0

**Comment by nr-ahemsath** [comment]
Hi @jtim08515.  Thanks for bringing this to our attention.  Unfortunately, we are not the maintainers of those Chocolatey packages for our agent.  Have you tried reaching out to any of the three package maintainers listed on the left sidebar?

I do see that 9.3.0 and 9.4.0 are in some kind of limbo state due to failed validation testing; however, I don't seem to have any visibility into what is failing or why, so I'm not sure what needs to be done.

**Comment by nr-ahemsath** [comment]
@jtim08515: upon further examination, it looks like the validation is failing due to a broken `<iconUrl>` element in our NuGet package metadata, so this is something we can address.  I'm working with our website team to figure out what URL to use instead.
